#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Next container image
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  build:
    env:
      IMAGE_NAME: quay.io/eclipse/che-backup-server-rest
    runs-on: ubuntu-20.04
    steps:
      - name: Clone source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        run: |
          SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
          PLATFORMS=$(cat PLATFORMS)
          echo "Build and push image ${IMAGE_NAME}:${SHORT_COMMIT_HASH}"
          docker buildx build --platform "${PLATFORMS}" -t "${IMAGE_NAME}:${SHORT_COMMIT_HASH}" --push .
          docker tag ${IMAGE_NAME}:${SHORT_COMMIT_HASH} ${IMAGE_NAME}:next
      - name: Create failure MM message
        if: ${{ failure() }}
        run: |
          echo "{\"text\":\":no_entry_sign: Next Che Backup Server build has failed: https://github.com/che-dockerfiles/che-backup-server-rest/actions/workflows/next-build.yml\"}" > mattermost.json
      - name: Send MM message
        if: ${{ failure() }}
        uses: mattermost/action-mattermost-notify@1.1.0
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_CHANNEL: eclipse-che-ci
          MATTERMOST_USERNAME: che-bot
