#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: PR check
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dockerfile: ['Dockerfile', 'rhel.Dockerfile']
    steps:
    - name: Clone source code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker build
      run: |
        PLATFORMS=$(cat PLATFORMS)
        docker buildx build --platform "${PLATFORMS}" -f ${{matrix.dockerfile}} .
